VERSION 0.8


ARG --global DOCKER_IMAGES_TARGETS=""
ARG --global DOCKER_IMAGE_PREFIX="cf"
ARG --global DOCKER_IMAGES_EXTRA_TAGS=""
ARG --global DOCKER_REGISTRIES=""
ARG --global HUB_DOCKER_COM_USER="cardanofoundation"
ARG --global PUSH=false

ALL:
  FUNCTION
  LOCALLY
  FOR image_target IN $DOCKER_IMAGES_TARGETS
    BUILD +$image_target --PUSH=$PUSH
  END

DOCKER_PUBLISH:
  FUNCTION
  BUILD +all --PUSH=$PUSH 

DOCKER_LABELS:
  FUNCTION
  ARG LABELS
  LET KEY=""
  LET VAL=""
  FOR --sep , pair IN $LABELS
    SET KEY=$(echo $pair | awk -F= '{print $1}')
    SET VAL=$(echo $pair | awk -F= '{print $2}')
    RUN echo $KEY=$VAL
    LABEL $KEY=$VAL
  END

docker-tag-n-push:
  ARG SRC_IMAGE
  ARG DST_IMAGE
  ARG PUSH
  LOCALLY
  RUN echo docker tag $SRC_IMAGE $DST_IMAGE && \
      docker tag $SRC_IMAGE $DST_IMAGE
  RUN if [ "$PUSH" = "true" ]; then docker push $DST_IMAGE; fi

DOCKER_TAG_N_PUSH:
  FUNCTION
  ARG EARTHLY_GIT_SHORT_HASH
  ARG PUSH # we use this as --push is not supported in LOCALLY blocks
  ARG TARGET_PLATFORM # if specified, only the platform-specific tags will be pushed
  ARG DOCKER_IMAGE_NAME
  ARG DOCKER_IMAGES_EXTRA_TAGS
  ARG DOCKER_REGISTRIES
  LOCALLY

  IF [ "$TARGET_PLATFORM" != "" ]
    LET TARGET_PLATFORM_TAG="_$(echo $TARGET_PLATFORM | sed 's|/|_|g')"
  END
  LET LATEST_IMAGE_TAG=latest${TARGET_PLATFORM_TAG}
  LET COMMIT_TAG=${EARTHLY_GIT_SHORT_HASH}
  LET IMAGE_TAG=""

  FOR registry IN $DOCKER_REGISTRIES
    # Push the extra tags
    FOR image_tag IN $DOCKER_IMAGES_EXTRA_TAGS $COMMIT_TAG

      SET IMAGE_TAG=${image_tag}${TARGET_PLATFORM_TAG}

      IF [ "$registry" = "hub.docker.com" ]
        BUILD +docker-tag-n-push \
          --SRC_IMAGE=${DOCKER_IMAGE_NAME}:${LATEST_IMAGE_TAG} \
          --DST_IMAGE=${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${IMAGE_TAG} \
          --PUSH=$PUSH
      ELSE
        BUILD +docker-tag-n-push \
          --SRC_IMAGE=${DOCKER_IMAGE_NAME}:${LATEST_IMAGE_TAG} \
          --DST_IMAGE=${registry}/${DOCKER_IMAGE_NAME}:${IMAGE_TAG} \
          --PUSH=$PUSH
      END
    END
  END

docker-merge-manifest:
  ARG MANIFEST
  ARG PLATFORM_MANIFEST
  ARG PUSH
  LOCALLY
  RUN echo docker manifest create ${MANIFEST} \
    --amend ${PLATFORM_MANIFEST} && \
    docker manifest create ${MANIFEST} \
    --amend ${PLATFORM_MANIFEST}
  RUN if [ "$PUSH" = "true" ]; then docker manifest push ${MANIFEST}; fi


DOCKER_MANIFESTS_MERGE:
  FUNCTION
  ARG EARTHLY_GIT_SHORT_HASH
  ARG PLATFORMS
  ARG DOCKER_IMAGE_NAME
  ARG DOCKER_IMAGES_EXTRA_TAGS
  ARG DOCKER_REGISTRIES
  ARG PUSH
  LOCALLY
  LET PLATFORM_TAGS=$(echo $PLATFORMS | sed 's|/|_|g')

  FOR registry IN $DOCKER_REGISTRIES
    FOR image_tag IN $DOCKER_IMAGES_EXTRA_TAGS ${EARTHLY_GIT_SHORT_HASH}
      FOR platform IN $PLATFORM_TAGS
        IF [ "$registry" = "hub.docker.com" ]
          BUILD +docker-merge-manifest \
            --MANIFEST=${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${image_tag} \
            --PLATFORM_MANIFEST=${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${image_tag}_${platform} \
            --PUSH=$PUSH
        ELSE
          BUILD +docker-merge-manifest \
            --MANIFEST=${registry}/${DOCKER_IMAGE_NAME}:${image_tag} \
            --PLATFORM_MANIFEST=${registry}/${DOCKER_IMAGE_NAME}:${image_tag}_${platform} \
            --PUSH=$PUSH
        END
      END
    END
  END
