VERSION 0.8


ARG --global DOCKER_IMAGES_TARGETS=""
ARG --global DOCKER_IMAGE_PREFIX="cf"
ARG --global DOCKER_IMAGES_EXTRA_TAGS=""
ARG --global DOCKER_REGISTRIES=""
ARG --global HUB_DOCKER_COM_USER="cardanofoundation"
ARG --global PUSH=false

ALL:
  FUNCTION
  LOCALLY
  FOR image_target IN $DOCKER_IMAGES_TARGETS
    BUILD +$image_target --PUSH=$PUSH
  END

DOCKER_PUBLISH:
  FUNCTION
  BUILD +all --PUSH=$PUSH 

DOCKER_LABELS:
  FUNCTION
  ARG LABELS
  LET KEY=""
  LET VAL=""
  FOR line IN $LABELS
    SET KEY=$(echo $line | awk -F= '{print $1}')
    SET VAL=$(echo $line | awk -F= '{print $2}')
    RUN echo $KEY=$VAL
    LABEL $KEY=$VAL
  END

DOCKER_TAG_N_PUSH:
  FUNCTION
  ARG EARTHLY_GIT_SHORT_HASH
  ARG PUSH # we use this as --push is not supported in LOCALLY blocks
  ARG DOCKER_IMAGE_NAME
  ARG DOCKER_IMAGES_EXTRA_TAGS
  LOCALLY
  FOR registry IN $DOCKER_REGISTRIES
    FOR image_tag IN $DOCKER_IMAGES_EXTRA_TAGS
      IF [ "$registry" = "hub.docker.com" ]
        RUN echo docker tag ${DOCKER_IMAGE_NAME}:latest ${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${image_tag} && \
            docker tag ${DOCKER_IMAGE_NAME}:latest ${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${image_tag}
        RUN if [ "$PUSH" = "true" ]; then docker push ${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${image_tag}; fi
      ELSE
        RUN echo docker tag ${DOCKER_IMAGE_NAME}:latest ${registry}/${DOCKER_IMAGE_NAME}:${image_tag} && \
            docker tag ${DOCKER_IMAGE_NAME}:latest ${registry}/${DOCKER_IMAGE_NAME}:${image_tag}
        RUN if [ "$PUSH" = "true" ]; then docker push ${registry}/${DOCKER_IMAGE_NAME}:${image_tag}; fi
      END
    END
    IF [ "$registry" = "hub.docker.com" ]
      RUN echo docker tag ${DOCKER_IMAGE_NAME}:latest ${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${EARTHLY_GIT_SHORT_HASH} && \
          docker tag ${DOCKER_IMAGE_NAME}:latest ${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${EARTHLY_GIT_SHORT_HASH}
      RUN if [ "$PUSH" = "true" ]; then docker push ${HUB_DOCKER_COM_USER}/${DOCKER_IMAGE_NAME}:${EARTHLY_GIT_SHORT_HASH}; fi
    ELSE
      RUN echo docker tag ${DOCKER_IMAGE_NAME}:latest ${registry}/${DOCKER_IMAGE_NAME}:${EARTHLY_GIT_SHORT_HASH} && \
          docker tag ${DOCKER_IMAGE_NAME}:latest ${registry}/${DOCKER_IMAGE_NAME}:${EARTHLY_GIT_SHORT_HASH}
      RUN if [ "$PUSH" = "true" ]; then docker push ${registry}/${DOCKER_IMAGE_NAME}:${EARTHLY_GIT_SHORT_HASH}; fi
    END
  END
