name: cf-gha-dispatch-event

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
  GITHUB_REPO:
    description: 'GitHub repository'
    required: true
  EVENT_TYPE:
    description: 'Event type'
    required: true
  GIT_SHORT_COMMIT:
    description: 'Short commit hash'
    required: false
  TRIGGERING_EVENT:
    description: 'Event triggering the workflow'
    required: false
  TRIGGERING_REF:
    description: 'Ref triggering the workflow'
    required: false
  TRIGGERING_BRANCH:
    description: 'Branch triggering the workflow'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Triggering a workflow in private repository
      shell: bash
      run: |
        
        event_type=${EVENT_TYPE}

        cat > /tmp/payload.json <<EOF
        {
          "event_type": "${EVENT_TYPE}",
          "client_payload": {
              "TRIGGERING_EVENT": "${GITHUB_EVENT_NAME}",
              "TRIGGERING_REF": "${TRIGGERING_REF}",
              "TRIGGERING_BRANCH": "${TRIGGERING_BRANCH}",
              "GIT_SHORT_COMMIT": "${GIT_SHORT_COMMIT}"
          }
        }
        EOF

        jq . /tmp/payload.json
    
        curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ inputs.GITHUB_REPO }}/dispatches \
          -d @/tmp/payload.json
